name: fin_sentiment
channels:
  - pypi
  - anaconda
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - jupyter=1.0.0
  - pandas=0.23.4
  - python=3.7.3
  - numpy==1.16.3
  - nltk
  - tqdm
  - ipykernel=5.1.3
  - transformers=4.1.1
  - pip:
    - joblib==0.13.2
    - scikit-learn==0.21.2
    - spacy==2.1.4
    - torch==1.10.1
    - textblob
    - beautifulsoup4
    - requests-html
    - tokenizers==0.10.3
    - numpy==1.20
    - json2html